
name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
      - name: Archive Release
        run: |
          mkdir -p dist/samenwerkende-catalogi
          rsync -av ./ ./dist/samenwerkende-catalogi --exclude /.git --exclude /.github --exclude .gitignore --exclude 'composer.*' --exclude Dockerfile-php-build --exclude DOCKER_ENV --exclude docker_tag --exclude output.log
          cd dist
          zip -r ../samenwerkende-catalogi.zip ./samenwerkende-catalogi
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: samenwerkende-catalogi.zip
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
