
name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'samenwerkende-catalogi.zip'
          exclusions: '*.git*'
      - name: Release
        uses: fnkr/github-action-ght@v1
        env:
          GHR_PATH: samenwerkende-catalogi.zip
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
